### ISSUE TITLE
Changing sample rate on TLA2518.

### ISSUE THREAD

**Issue by coulomb-IQ** [dlyckelid/IOExpander-TLA2518#2]
Hi David, 

I wanted to ask if you had experimented with a slower sample rate by setting the OPMODE_CFG register.
I have a custom board with ESP32-WROOM-32UE that communicates effectively with the TLA2528 with i2c.  My issue is that as soon as I slow the sampling rate slower than 10.42 kSPS (0b00010011), I get the dreaded i2c timeout 263 from the Wire library.  Yes, I'm using the ESP Arduino environment inside VS Code and PIO.  I just cant bring myself yet to tackle the Espressif IDE.
Despite trawling the internet looking for a solution, I'm considering just switching to the TLA2518 and SPI communications, hence the question.  Ultimately, I would like to know if 0.16 kSPS is possible (0b00011111)?

Thanks for any assistance you may be able to offer.  Best way to contact me is jason.gillies@coulombiq.com.au
Thanks
Jason

**Comment by dlyckelid** [comment]
Hi!

Sorry for the late reply. I have not used the TLA2528 with I2C at all. I just added it because I knew that some people would need it.
I think switching to SPI would be good atleast to try to solve the issue. My usecase for the chip is very narrow so I have not even experimented with different samplerates and just wrote in settings as they where defined in the datasheet.

**Comment by coulomb-IQ** [comment]
Thanks for the reply David, 
I've done the switch to the TLA2518 and SPI but have now had to add a faster level shifter than my usual MOSFET driver.  The MOSFET works great for I2C but will be too slow for SPI (I'm getting data corruption, observed on a digital scope).  New boards are currently on the way.
